{% set name = "gleam" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gleam-lang/gleam/archive/v{{ version }}.tar.gz
  sha256: 86bdaa4b7803230bd434044e0632f6d31246a8514fd68d10c3add9dfff400544

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - gleam --help

about:
  home: https://github.com/gleam-lang/gleam
  license: MIT
  license_file:
    - LICENCE
    - THIRDPARTY.yml
  summary: A friendly language for building type-safe, scalable systems!
  dev_url: https://github.com/gleam-lang/gleam

extra:
  recipe-maintainers:
    - danielnachun
