{% set name = "gleam" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gleam-lang/gleam/archive/v{{ version }}.tar.gz
  sha256: 9955f255567b7e975505ab3633841bc0650afabd4bb31f3a337bce91e2fc29de

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - gleam --help

about:
  home: https://github.com/gleam-lang/gleam
  license: MIT
  license_file:
    - LICENCE
    - THIRDPARTY.yml
  summary: A friendly language for building type-safe, scalable systems!
  dev_url: https://github.com/gleam-lang/gleam

extra:
  recipe-maintainers:
    - danielnachun
