{% set name = "gleam" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gleam-lang/gleam/archive/v{{ version }}.tar.gz
  sha256: e4362bca4e82cfdbbb5a09f2bfa9a67fe6d766f893c6bed8852694aca9c30bc9

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - gleam --help

about:
  home: https://github.com/gleam-lang/gleam
  license: MIT
  license_file:
    - LICENCE
    - THIRDPARTY.yml
  summary: A friendly language for building type-safe, scalable systems!
  dev_url: https://github.com/gleam-lang/gleam

extra:
  recipe-maintainers:
    - danielnachun
