context:
  version: "1.15.4"

package:
  name: gleam
  version: ${{ version }}

source:
  url: https://github.com/gleam-lang/gleam/archive/v${{ version }}.tar.gz
  sha256: 268c635591bd165e0e1d1fdf7cca9d7da141b6aff58b84a43397664cb270a870

build:
  number: 0
  skip: ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - gleam --help

about:
  license: MIT
  license_file:
    - LICENCE
    - THIRDPARTY.yml
  summary: A friendly language for building type-safe, scalable systems!
  homepage: https://github.com/gleam-lang/gleam
  repository: https://github.com/gleam-lang/gleam

extra:
  recipe-maintainers:
    - tdejager
    - danielnachun
