context:
  version: "1.18.0"

package:
  name: gleam
  version: ${{ version }}

source:
  url: https://github.com/gleam-lang/gleam/archive/v${{ version }}.tar.gz
  sha256: a89e5fdb6c56c2063fd8d3bff9e06ac6ff45e102d17da4f9655e79038ef02e89

build:
  number: 0
  skip: ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - gleam --help

about:
  license: MIT
  license_file:
    - LICENCE
    - THIRDPARTY.yml
  summary: A friendly language for building type-safe, scalable systems!
  homepage: https://github.com/gleam-lang/gleam
  repository: https://github.com/gleam-lang/gleam

extra:
  recipe-maintainers:
    - tdejager
    - danielnachun
