context:
  version: "1.17.0"

package:
  name: gleam
  version: ${{ version }}

source:
  url: https://github.com/gleam-lang/gleam/archive/v${{ version }}.tar.gz
  sha256: 644db4b25596d5f27f03614ef1cc10646baaabbd559407acc278bb24c6502f8b

build:
  number: 0
  skip: ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - gleam --help

about:
  license: MIT
  license_file:
    - LICENCE
    - THIRDPARTY.yml
  summary: A friendly language for building type-safe, scalable systems!
  homepage: https://github.com/gleam-lang/gleam
  repository: https://github.com/gleam-lang/gleam

extra:
  recipe-maintainers:
    - tdejager
    - danielnachun
